# SPDX-FileCopyrightText: 2006-2025, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: CodeChecker

on:
  schedule:
    - cron: "0 2 * * WED"
  workflow_dispatch:

concurrency:
  group: codechecker-${{ github.ref }}
  cancel-in-progress: true

env:
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: CodeChecker
    runs-on: ubuntu-latest
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    container:
      image: ghcr.io/seqan/clang-19
      volumes:
        - /home/runner:/home/runner
    steps:
      - name: Run CodeChecker
        uses: seqan/actions/codechecker@main
        with:
          configure_path: ../test/unit
          deploy_host: ${{ secrets.DEPLOY_HOST }}
          deploy_user: ${{ secrets.DEPLOY_USER }}
          deploy_ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
          deploy_path: ${{ secrets.DEPLOY_CODECHECKER_PATH }}
