# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Update CPM

on:
  schedule:
    - cron: "0 12 * * SAT"
  workflow_dispatch:

env:
  TZ: Europe/Berlin

concurrency:
  group: update-cpm-actions
  cancel-in-progress: true

jobs:
  update_cpm:
    name: Update CPM
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Run update CPM
        uses: seqan/actions/update_cpm_package_lock@main
        with:
          token: ${{ secrets.SEQAN_ACTIONS_PAT }}
          gpg_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
          gpg_passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
          package_lock_file: cmake/package-lock.cmake
