# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Lint

on:
  pull_request_target:

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  # Cancel other workflows that are dependent on this workflow by adding jobs that have the same concurrency group.
  cancel_linux:
    name: Cancel running Workflows
    concurrency:
      group: linux-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: "Cancel Linux"
        run: echo "Cancelling Linux"
  cancel_macos:
    name: Cancel running Workflows
    concurrency:
      group: macos-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: "Cancel macOS"
        run: echo "Cancelling macOS"
  cancel_misc:
    name: Cancel running Workflows
    concurrency:
      group: misc-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: "Cancel Misc"
        run: echo "Cancelling Misc"
  cancel_coverage:
    name: Cancel running Workflows
    concurrency:
      group: coverage-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: "Cancel Coverage"
        run: echo "Cancelling Coverage"
  cancel_cmake:
    name: Cancel running Workflows
    concurrency:
      group: cmake-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: "Cancel CMake"
        run: echo "Cancelling CMake"
  cancel_documentation:
    name: Cancel running Workflows
    concurrency:
      group: documentation-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: "Cancel Documentation"
        run: echo "Cancelling Documentation"
  lint:
    name: Lint
    concurrency:
      group: lint-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    needs: [cancel_linux, cancel_macos, cancel_misc, cancel_coverage, cancel_cmake, cancel_documentation]
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Run lint
        uses: seqan/actions/lint@main
        with:
          clang_format: 18
          token: ${{ secrets.SEQAN_ACTIONS_PAT }}
          gpg_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
          gpg_passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
