name: SeqAn3 cmake-format

on:
  # Will always run on the default branch
  schedule:
    - cron: "0 7 * * SUN"
  # Enables a manual trigger, may run on any branch. Only works on seqan/seqan3.
  workflow_dispatch:

concurrency:
  group: cmake-format-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CMAKE_VERSION: 3.10.3
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -exo pipefail {0}

jobs:
  build:
    name: cmake-format
    runs-on: ubuntu-22.04
    timeout-minutes: 300
    if: github.repository_owner == 'seqan'
    steps:
      - name: Checkout SeqAn3
        uses: actions/checkout@v2
        with:
          path: seqan3
          submodules: false

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install cmakelang[YAML]

      - name: Run cmake-format
        run: |
          find seqan3 \( -iname CMakeLists.txt -or -iname "*.cmake" \) \
          -and -not -path "./submodules/*" \
          -and -not -path "./build/*" | \
          xargs cmake-format --config-files seqan3/.cmake-format.yaml --in-place

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          workdir: seqan3
          gpg_private_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
          passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: seqan3
          token: ${{ secrets.SEQAN_ACTIONS_PAT }}
          push-to-fork: seqan-actions/seqan3
          commit-message: '[CRON] cmake-format'
          committer: seqan-actions[bot] <seqan-actions@users.noreply.github.com>
          author: seqan-actions[bot] <seqan-actions@users.noreply.github.com>
          branch: actions/cmake-format/${{github.repository}}
          delete-branch: true
          title: '[CRON] cmake-format'
          body: Auto-generated cmake-format changes
