name: Deploy documentation (https://docs.seqan.de/)

on:
  push:
    branches:
      - master
  # Enables a manual trigger, may run on any branch
  workflow_dispatch:

concurrency:
  group: docs-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  deploy_documentation:
    name: Deploy Documentation
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.16.9

      - name: Install Doxygen
        uses: seqan/actions/setup-doxygen@main
        with:
          doxygen: 1.9.6

      - name: Load cached documentation
        uses: actions/cache@v3
        with:
          path: doc-build
          key: ${{ runner.os }}-documentation-1.9.6

      - name: Build documentation
        run: |
          mkdir -p doc-build
          cd doc-build
          cmake ../test/documentation
          make -j2 download-cppreference-doxygen-web-tag
          ctest . -j2 --output-on-failure

      - name: Deploy User Documentation
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
        with:
          flags: '-zr --delete --timeout=60 --omit-dir-times'
          src: 'doc-build/doc_usr/html/'
          dest: '$REMOTE_USER@$REMOTE_HOST:$TARGET/3-master-user'

      - name: Deploy Developer Documentation
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
        with:
          flags: '-zr --delete --timeout=60 --omit-dir-times'
          src: 'doc-build/doc_dev/html/'
          dest: '$REMOTE_USER@$REMOTE_HOST:$TARGET/3-master-dev'
