name: Deploy documentation (https://docs.seqan.de/)

on:
  push:
    branches:
      - master

env:
  CMAKE_VERSION: 3.8.2
  DOXYGEN_VERSION: 1.9.1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  deploy_documentation:
    name: Deploy Documentation
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure APT
        run: bash .github/workflows/scripts/configure_apt.sh

      - name: Install CMake
        run: bash .github/workflows/scripts/install_cmake.sh

      - name: Install Doxygen
        run: bash .github/workflows/scripts/install_doxygen.sh

      - name: Load cached documentation
        uses: actions/cache@v2
        with:
          path: doc-build
          key: ${{ runner.os }}-documentation-${{ env.DOXYGEN_VERSION }}

      - name: Build documentation
        run: |
          mkdir -p doc-build
          cd doc-build
          cmake ../test/documentation
          make download-cppreference-doxygen-web-tag
          ctest . -j 2 --output-on-failure

      - name: Deploy User Documentation
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
        with:
          flags: '-azr --delete --timeout=60 --omit-dir-times'
          src: 'doc-build/doc_usr/html/'
          dest: '$REMOTE_USER@$REMOTE_HOST:$TARGET/3-master-user'

      - name: Deploy Developer Documentation
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
        with:
          flags: '-azr --delete --timeout=60 --omit-dir-times'
          src: 'doc-build/doc_dev/html/'
          dest: '$REMOTE_USER@$REMOTE_HOST:$TARGET/3-master-dev'
